#pragma once

#include "Precompiled.hpp"

/*
    Build Utility

    Stores information generated by the build system.
    Will not work with executable outside of the build directory.
*/

namespace Build
{
    // Loads info generated by the build system.
    void Initialize();

    // Gets the working directory specified by the build system.
    std::string GetWorkingDir();

    // Gets the source directory specified by the build system.
    std::string GetSourceDir();
}
